/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.PatientClass;
import javax.swing.ImageIcon;

/**
 *
 * @author 91903
 */
public class ViewJPanel extends javax.swing.JPanel {
    ImageIcon profilePicture;
    PatientClass p1;

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel() {
        initComponents();
    }
public ViewJPanel(PatientClass p1){
        this.p1=p1;
        initComponents();
        populateData();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelLname = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        patientTypeJLabel = new javax.swing.JLabel();
        PatientTypeJComboBox = new javax.swing.JComboBox<>();
        imageJButton = new javax.swing.JButton();
        imageJLabel = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        imgJlabel = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 102, 102));

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelName.setText("First Name:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLname.setText("Last Name:");

        jLabelGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGender.setText("Gender:");

        jLabelAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelAge.setText("Age:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail.setText("Email Id:");

        patientTypeJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientTypeJLabel.setText("Patient Type:");

        PatientTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appointment", "Walk-in" }));
        PatientTypeJComboBox.setSelectedIndex(-1);
        PatientTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientTypeJComboBoxActionPerformed(evt);
            }
        });

        imageJButton.setText("Upload");

        imageJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imageJLabel.setText("Select Image:");

        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));
        jComboBoxGender.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientTypeJLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelLname)
                                .addComponent(jLabelName)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelAge)
                                    .addGap(22, 22, 22))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(imageJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldLname)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldAge)
                            .addComponent(PatientTypeJComboBox, 0, 151, Short.MAX_VALUE)
                            .addComponent(imageJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSubmit)
                        .addGap(137, 137, 137)))
                .addComponent(imgJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLname)
                    .addComponent(jTextFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelGender))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAge)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientTypeJLabel)
                    .addComponent(PatientTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageJLabel)
                    .addComponent(imageJButton)
                    .addComponent(imgJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSubmit)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void PatientTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientTypeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientTypeJComboBoxActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubmitActionPerformed

public void populateData(){
        this.jTextFieldName.setText(p1.getName());
        this.jTextFieldLname.setText(p1.getLast_name());
        this.jTextFieldAge.setText(String.valueOf(p1.getAge()));
        //this.jTextFieldAge.setTransferHandler(p1.getAge());
        this.jTextFieldEmail.setText(p1.getEmail());
        //String gender = p1.getGender();
//        if(gender.equals("Male")){
            //this.buttonGroupGender.setSelected(this.jRadioButtonMale.getModel(), true);
        
        //}else if(gender.equals("Female")){
            //this.buttonGroupGender.setSelected(this.jRadioButtonFemale.getModel(), true);
        //}else{
          //  this.buttonGroupGender.setSelected(this.jRadioButtonOthers.getModel(), true);
        
        //}
        this.PatientTypeJComboBox.setSelectedItem(p1.getPatientType());
        this.jComboBoxGender.setSelectedItem(p1.getGender());
        this.imgJlabel.setIcon(p1.getProfilePicture());
       // this.buttonGroupGender.setSelected(m, true);
       
       
       // -----------------------------       For Disabled editing on View Side
       this.jTextFieldName.setEnabled(false);
       this.jTextFieldLname.setEnabled(false);
       this.jTextFieldAge.setEnabled(false);
       this.jTextFieldEmail.setEnabled(false);
       
       
       this.jComboBoxGender.setEnabled(false);
       this.jComboBoxGender.setEnabled(false);
       this.jComboBoxGender.setEnabled(false);
       this.PatientTypeJComboBox.setEnabled(false);
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PatientTypeJComboBox;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton imageJButton;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JLabel imgJlabel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLname;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JLabel patientTypeJLabel;
    // End of variables declaration//GEN-END:variables
}
