/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.PatientClass;
/**
 *
 * @author 91903
 */
public class FormJPanel extends javax.swing.JPanel {
ImageIcon profilePicture;
JPanel bottomjPanel;
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel(JPanel bottomjPanel) {
        this.bottomjPanel=bottomjPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelLname = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        patientTypeJLabel = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jTextFieldLname = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        PatientTypeJComboBox = new javax.swing.JComboBox<>();
        imgJlabel = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxGender = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 0));

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelName.setText("First Name:");

        jLabelLname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLname.setText("Last Name:");

        jLabelGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGender.setText("Gender:");

        jLabelAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelAge.setText("Age:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail.setText("Email Id:");

        patientTypeJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientTypeJLabel.setText("Patient Type:");

        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });

        PatientTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appointment", "Walk-in" }));
        PatientTypeJComboBox.setSelectedIndex(-1);
        PatientTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientTypeJComboBoxActionPerformed(evt);
            }
        });

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));
        jComboBoxGender.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelAge)
                                    .addGap(10, 10, 10)))
                            .addComponent(patientTypeJLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelLname)
                                .addComponent(jLabelName)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLname)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldAge)
                            .addComponent(PatientTypeJComboBox, 0, 151, Short.MAX_VALUE)
                            .addComponent(jTextFieldName)
                            .addComponent(jComboBoxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(imgJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButtonSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGender))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAge))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientTypeJLabel))))
                .addGap(9, 9, 9)
                .addComponent(jButtonSubmit)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        try
        {
            String name=this.jTextFieldName.getText();
           // String gender=this.buttonGroupGender.getSelection().getActionCommand();
            String patientType= this.PatientTypeJComboBox.getSelectedItem().toString();
            String Gender= this.jComboBoxGender.getSelectedItem().toString();
            int age= Integer.parseInt(jTextFieldAge.getText());
            String last_name = this.jTextFieldLname.getText();
            String email=this.jTextFieldEmail.getText();
            String msgtxt= this.jTextFieldEmail.getText();
            String displayMessage= "Name: " +name+" Last Name: "+last_name+ " Gender: "+Gender+" Age: "+age+"Email: "+email+" Patient Type "+patientType+" Message Box "+ msgtxt;
            System.out.println(this.jTextFieldName.getText());
            System.out.println(this.jTextFieldLname.getText());
            //System.out.println(this.buttonGroupGender.getSelection().getActionCommand());
            System.out.println(this.jTextFieldEmail.getText());
            System.out.println(this.jTextFieldAge.getText());
            System.out.println(this.jTextFieldAge.getText());
            //System.out.println(this.Gender.getText());

            //if(name.equals("")|| patientType.equals("")){
                //JOptionPane.showMessageDialog(this, displayMessage, "Success", HEIGHT, this.profilePicture);
              //  displayMessage= " Maybe you forgot to enter some details! Please fill all the Details. Thank You... ";
              

            //}else{
              //  displayMessage="Name is: "+ name+"Last Name: "+last_name+ " Gender is: "+Gender+" Patient Type: "+patientType+" Age:  "+age+"Email: "+email;
                //JOptionPane.showMessageDialog(this, "Invalid Details!!!  Please enter valid details");
            //}
 if(name.equals("")&& patientType.equals("")&& age>100 && last_name.equals("") && email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$") ){
                JOptionPane.showMessageDialog(this, displayMessage, "Success", HEIGHT, this.profilePicture);
 JOptionPane.showMessageDialog(this, displayMessage, "Success", HEIGHT, this.profilePicture);}
              //  displayMessage= " Maybe you forgot to enter some details! Please fill all the Deatails. Thank You... ";
              

            else{
                //displayMessage="Name is: "+ name+"Last Name: "+last_name+ " Gender is: "+gender+" Patient Type: "+patientType+" Age:  "+age+"Email: "+email;
                JOptionPane.showMessageDialog(this, "Kindly check your Details Again!!");
            }
            //JOptionPane.showMessageDialog(this, displayMessage);
            //JOptionPane.showMessageDialog(this, displayMessage, "Success", HEIGHT, this.profilePicture);
            
            JOptionPane.showMessageDialog(this, displayMessage, "Success", HEIGHT, this.profilePicture);
            PatientClass p1=new PatientClass();
            p1.setName(name);
            p1.setGender(Gender);
            p1.setPatientType(patientType);
            p1.setAge(age);
            p1.setEmail(email);
            p1.setLast_name(last_name);
            p1.setProfilePicture(profilePicture);
            
            ViewJPanel1 newViewJPanel= new  ViewJPanel1(p1); 
            this.bottomjPanel.add(newViewJPanel); 
            CardLayout layout = (CardLayout) this.bottomjPanel.getLayout();
            layout.next(bottomjPanel);
        }
        catch(NullPointerException ne)
        {
            String errorMessage="You must enter all the Details";
            JOptionPane.showMessageDialog(this, errorMessage);
        }
        catch(Exception e)
        {
            System.out.println("Exception has occured.");
            System.out.println(e);

    }//GEN-LAST:event_jButtonSubmitActionPerformed
    }
    private void PatientTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientTypeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientTypeJComboBoxActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PatientTypeJComboBox;
    private javax.swing.JLabel imgJlabel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLname;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JLabel patientTypeJLabel;
    // End of variables declaration//GEN-END:variables
}
